### ISSUE TITLE
no "Custom" in endless os

### ISSUE THREAD

**Issue by satellitee** [flathub/org.fedoraproject.MediaWriter#5]
I have endless os installed (from 32 GB USB ) 
Unable to use Fedora Media Writer to see downloaded .iso or raw files in "custom" but  can use files downloaded by FMW and write them to USB normally.

**Comment by satellitee** [comment]
workaround: use "disks" to restore the Fedora-Mate-armhfp-Rawhide-20190616.n.0-sda.raw file to microSD
Started in RpiB3+

**Comment by satellitee** [comment]
<ramcq> sandboxed apps have to use portal APIs to fetch local files
is it possible to access "Downloads" directory?; "disks" does

**Comment by MartinBriza** [comment]
I don't understand most of this report, except for that you can't access your files using the "Custom" image option. Sounds like a problem with FS permissions (see the JSON manifest, I have put "host" filesystem access to it), because FMW should be able to access the files. You're right we should use the portal APIs, though.

**Comment by grulja** [comment]
FMW already uses xdg-desktop-portal on Linux. I think this issue can be closed.
